DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(500) NOT NULL UNIQUE,
    name varchar(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(1000),
    requestor_id bigint REFERENCES users(id),
    create_date timestamp without time zone
);

CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(500) NOT NULL,
    description varchar(1000) NOT NULL,
    available boolean default false,
    owner_id bigint REFERENCES users(id),
    request_id bigint REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1024) NOT NULL,
    item_id bigint REFERENCES items(id),
    author_id bigint REFERENCES users(id),
    created timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id bigint REFERENCES items(id),
    booker_id bigint REFERENCES users(id),
    status varchar(100) NOT NULL
);
